# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.check_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_1.setGeometry(QtCore.QRect(140, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.check_1.setFont(font)
        self.check_1.setObjectName("check_1")
        self.check_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_2.setGeometry(QtCore.QRect(140, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.check_2.setFont(font)
        self.check_2.setObjectName("check_2")
        self.check_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_3.setGeometry(QtCore.QRect(140, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.check_3.setFont(font)
        self.check_3.setObjectName("check_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 190, 351, 181))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 382, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.check_1.setText(_translate("MainWindow", "پیتزا اورجینال"))
        self.check_2.setText(_translate("MainWindow", "پیتزا پپرونی"))
        self.check_3.setText(_translate("MainWindow", "پیتزا قارچ"))
        self.label_2.setText(_translate("MainWindow", "منو غذا"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
